//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera.UI.Localize {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Camera.UI.Localize.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string textAdd {
            get {
                return ResourceManager.GetString("textAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string textAuth {
            get {
                return ResourceManager.GetString("textAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cabel.
        /// </summary>
        public static string textCabel {
            get {
                return ResourceManager.GetString("textCabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalogs.
        /// </summary>
        public static string textCameraCatalog {
            get {
                return ResourceManager.GetString("textCameraCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string textCameraName {
            get {
                return ResourceManager.GetString("textCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Camera.
        /// </summary>
        public static string textCameraObervable {
            get {
                return ResourceManager.GetString("textCameraObervable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cameras.
        /// </summary>
        public static string textCameras {
            get {
                return ResourceManager.GetString("textCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string textCancel {
            get {
                return ResourceManager.GetString("textCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change mail.
        /// </summary>
        public static string textChangeEmail {
            get {
                return ResourceManager.GetString("textChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail changed successfully!.
        /// </summary>
        public static string textChangeEmailSuccess {
            get {
                return ResourceManager.GetString("textChangeEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change language.
        /// </summary>
        public static string textChangeLanguage {
            get {
                return ResourceManager.GetString("textChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string textConnectTg {
            get {
                return ResourceManager.GetString("textConnectTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data for connection.
        /// </summary>
        public static string textDataConnection {
            get {
                return ResourceManager.GetString("textDataConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string textDelete {
            get {
                return ResourceManager.GetString("textDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string textEdit {
            get {
                return ResourceManager.GetString("textEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change of mail.
        /// </summary>
        public static string textEditEmail {
            get {
                return ResourceManager.GetString("textEditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string textEmail {
            get {
                return ResourceManager.GetString("textEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email is required.
        /// </summary>
        public static string textEmailIsRequired {
            get {
                return ResourceManager.GetString("textEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email is not template.
        /// </summary>
        public static string textEmailNotTemplate {
            get {
                return ResourceManager.GetString("textEmailNotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string textError {
            get {
                return ResourceManager.GetString("textError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t find this camera, try another one!.
        /// </summary>
        public static string textErrorLoadCamera {
            get {
                return ResourceManager.GetString("textErrorLoadCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ethernet.
        /// </summary>
        public static string textEthernet {
            get {
                return ResourceManager.GetString("textEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string textInfo {
            get {
                return ResourceManager.GetString("textInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string textLogin {
            get {
                return ResourceManager.GetString("textLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string textLogout {
            get {
                return ResourceManager.GetString("textLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification.
        /// </summary>
        public static string textNotification {
            get {
                return ResourceManager.GetString("textNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string textNotificationName {
            get {
                return ResourceManager.GetString("textNotificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string textOptions {
            get {
                return ResourceManager.GetString("textOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string textPassword {
            get {
                return ResourceManager.GetString("textPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is required.
        /// </summary>
        public static string textPasswordIsRequired {
            get {
                return ResourceManager.GetString("textPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password not equals retry password.
        /// </summary>
        public static string textPasswordNotEqualsRetryPassowrd {
            get {
                return ResourceManager.GetString("textPasswordNotEqualsRetryPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipient data.
        /// </summary>
        public static string textRecipientData {
            get {
                return ResourceManager.GetString("textRecipientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string textRegestration {
            get {
                return ResourceManager.GetString("textRegestration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember me.
        /// </summary>
        public static string textRememberMe {
            get {
                return ResourceManager.GetString("textRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry password.
        /// </summary>
        public static string textRetryPassword {
            get {
                return ResourceManager.GetString("textRetryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string textSave {
            get {
                return ResourceManager.GetString("textSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string textSelect {
            get {
                return ResourceManager.GetString("textSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected camera:.
        /// </summary>
        public static string textSelectedCamera {
            get {
                return ResourceManager.GetString("textSelectedCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string textSettings {
            get {
                return ResourceManager.GetString("textSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sing in.
        /// </summary>
        public static string textSignIn {
            get {
                return ResourceManager.GetString("textSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMS.
        /// </summary>
        public static string textSms {
            get {
                return ResourceManager.GetString("textSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram chatbot.
        /// </summary>
        public static string textTelegram {
            get {
                return ResourceManager.GetString("textTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection method.
        /// </summary>
        public static string textTypeConnection {
            get {
                return ResourceManager.GetString("textTypeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method of notification.
        /// </summary>
        public static string textTypeNotification {
            get {
                return ResourceManager.GetString("textTypeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable.
        /// </summary>
        public static string textUnconnectTg {
            get {
                return ResourceManager.GetString("textUnconnectTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to the web camera human motion detection software system!.
        /// </summary>
        public static string textWelcome {
            get {
                return ResourceManager.GetString("textWelcome", resourceCulture);
            }
        }
    }
}
